spring:
  profiles:
    active: "dev"

---

spring:
  profiles: dev
  jpa:
    hibernate:
      ddl-auto: create
  datasource:
    url: jdbc:mysql://localhost:3306/heroku_f55c067bb8163f0
    username: b0ae0c5f9fb986
    password: b6c0c0d7
server:
  host: localhost
  port: 9999