spring:
  profiles:
    active: "dev"

---

spring:
  profiles: dev
  jpa:
    hibernate:
      ddl-auto: create
  datasource:
    url: jdbc:mysql://localhost:3306/testBase
    username: testUser
    password: testPassword
server:
  host: localhost
  port: 9999